services:
  aspic:
    build:
      context: ./
      dockerfile: dockerfiles/app.dockerfile
    container_name: aspic_py
    restart: always
    ports:
      - "127.0.0.1:15191:15191"
    volumes:
      - ./data:/opt/dix/aspic/data
      # Пробрасываем статику для nginx:
      - ./app/static:/opt/dix/aspic/app/static
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15191/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - aspic_network

networks:
  aspic_network:
    driver: bridge